### ISSUE TITLE
Satellite image Data Source

### ISSUE THREAD

**Issue by mustafa-meco** [A-Stangeland/SolarDetection#9]
I am inquiring how to get the satellite image data of either US or France.

**Comment by A-Stangeland** [comment]
Hi @mustafa-meco,
Thank you for showing interest in my project.
The satellite images from the US were from the [DeepSolar project](http://web.stanford.edu/group/deepsolar/ds). It looks like you can download the dataset from kaggle: (https://www.kaggle.com/datasets/husseinawala/deepsolar/data)
The French satellite images were from a proprietary dataset, so sadly I don't think they are publicly available.
